### ISSUE TITLE
Make Portfolio Responsive and Cross platform Compatible & Secure the Firebase Credentials

### ISSUE THREAD

**Issue by harshtalrejaa** [harshtalrejaa/portfolio#1]

**Comment by NidhiGawde** [comment]
I would like to take up this issue

**Comment by harshtalrejaa** [comment]
Sure @NidhiGawde go ahead , waiting for updates !

**Comment by harshtalrejaa** [comment]
Also @NidhiGawde update the chnages in a readme file as well possibly

**Comment by NidhiGawde** [comment]
yes sure

**Comment by harshtalrejaa** [comment]
Thank you so much for resolving the issue @NidhiGawde !

**Comment by NidhiGawde** [comment]
welcome
